---
title: ""
author: "Igo da Costa Andrade"

# Metadados
booktitle: "Física"
booksubtitle: "um curso universitário. Vol. I - Mecânica"
bookauthors: "Alonso, M.; Finn, E. J."
bookaddres: "Rio de Janeiro"
bookpublisher: "Editora Blucher"
bookyear: "2011"
maincolor: "f10025"
chaptertitle: "Medidas e Unidades"
chapternumber: "2"

output: 
  bookdown::pdf_document2:
    template: template.tex
knit: >-
  (function(inputFile, encoding) {
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_dir = file.path(dirname(inputFile), "../output"),
      output_format = "bookdown::pdf_document2"
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python("~/anaconda3/envs/science/bin/python")

sci_fmt <- function(x, digits = 2) {
  s <- format(x, scientific = TRUE, digits = digits, decimal.mark = ",", big.mark = ".")
  parts <- strsplit(s, "e")[[1]]
  
  expoente <- as.integer(parts[2])
  
  if(expoente>-3 && expoente<3) {
    # Retorna sem notação científica quando o expoente é zero
    return(format(x, decimal.mark=",", big.mark=".", digits=digits))
  } else {
    # Retorna com notação científica
    return(paste0(parts[1], " \\times 10^{", expoente, "}"))
  }
}
```

```{python geral, include=FALSE}
import numpy as np
from math import pi

u = 1.6604e-27 # Unidade de massa atômica (u)
## Massas de átomos em kg
m_H_u = 1.00797 # Massa do átomo de Hidrogênio em unidades de massa atômica (u)
m_O_u = 15.9994 # Massa do átomo de Oxigênio em unidades de massa atômica (u)
m_C_u = 12.0000 # Massa do átomo de Carbono em unidades de massa atômica (u)
m_N_u = 14.0067 # Massa do átomo de Nitrogênio em unidades de massa atômica (u)

## Densidade relativa de gases
rho_H2 = 8.988e-5
rho_O2 = 1.42904e-3
rho_N2 = 1.25055e-3

## Densidade da água em g/cm^3
rho_agua = 1.0
```

```{python problemas, include=FALSE}
# Problema 2.1
m_H = m_H_u * u # Massa do átomo de Hidrogênio em kg
m_O = m_O_u * u # Massa do átomo de Oxigênio em kg

# Problema 2.2
m_h2o = 2*m_H + m_O # Massa da molécula de água em kg
N_1g = 1e-3 / m_h2o # Quantidade de moléculas de água em 1 grama
N_18g = 18 * N_1g # Quantidade de moléculas de água em 18 gramas

# Problema 2.3
N_C_1kg = 5.0188e25 # Quantidade de átomos do isótopo Carboo 12 em 1 kg
m_C = 1 / (N_C_1kg * m_C_u) # Massa do átomo de Carbono em kg

# Problema 2.4

## massas das moléculas de H2, O2 e N2
m_H2 = 2 * m_H_u * u # Massa da molécula de gás hidrogênio (kg/molécula)
m_O2 = 2 * m_O_u * u # Massa da molécula de gás oxigênio (kg/molécula)
m_N2 = 2 * m_N_u * u # Massa da molécula de gás nitrogênio (kg/molécula)

## Número de moléculas por metro cúbico
N_H2 = rho_H2 / m_H2
N_O2 = rho_O2 / m_O2
N_N2 = rho_N2 / m_N2

# Problema 2.5
## Ver dados do Problema 2.4
m_Ar_u = 0.2 * 2 * m_O_u + 0.8 * 2 * m_N_u # Massa molecular do ar em unidades de massa atômica
m_Ar = m_Ar_u * u # Massa molecular do ar em kg

## Quantidade de moléculas de ar em 1 cm3
N_Ar = (0.2 * rho_O2 + 0.8 * rho_N2) / (1000*m_Ar)
N_O2, N_N2 = 0.2 * N_Ar, 0.8*N_Ar

# Problema 2.6
rho_space = 1e-21 # Densidade do espaço interestelar em kg/m3
N_space = rho_space / m_H

# Problema 2.7
r = 2 ## cm
dh = 0.1 ## cm
dt = 2 ## h
v_evap = pi * r**2 * rho_agua * dh/dt
dNdt_evap = (v_evap * (1/1000) * (1/3600)) / (pi * r**2 * m_h2o)

# Problema 2.9
## Densidades em gramas por centímetro cúbico
rho_H2 = 8.988e-5
rho_H2O = 1.0
rho_Fe = 7.86

## Massa atômica/molecular
m_H2 = 2 * m_H_u * u
m_H2O = (2 * m_H_u + m_O_u) * u
m_Fe = 55.847 * u


## Volume por molécula
vol_H2 = m_H2 / (1000*rho_H2)
vol_H2O = m_H2O / (1000*rho_H2O)
vol_Fe =  m_Fe / (1000*rho_Fe)

## Modelo Cúbico
### Distância média 
l_H2 = vol_H2**(1/3)
l_H2O = vol_H2O**(1/3)
l_Fe = vol_Fe**(1/3)

## Modelo Esférico
### Distância média 
D_H2 = ((6/pi) * vol_H2)**(1/3)
D_H2O = ((6/pi) * vol_H2O)**(1/3)
D_Fe = ((6/pi) * vol_Fe)**(1/3)
```







\begin{enumerate}
  \item As massas atômicas, representadas na Tab. A.1, são expressas em \textit{unidades de massa atômica}, abreviadas por u. 1 u é igual a $1,6604 \times 10^{-27}$ kg. Calcule, em quilogramas em em gramas, as massas de (a) um átomo de hidrogênio e (b) um átomo de oxigênio.
  
  \iniSol
    \begin{enumerate}[label=(\alph*)]
      \item Hidrogênio
      \begin{align*}
        m_{kg} = \dfrac{1,6604 \times 10^{-27} \; \text{kg}}{1\;\text{u}} \times m_{u} & \Rightarrow m_{kg} = \dfrac{1,6604 \times 10^{-27} \; \text{kg}}{1\;\text{u}} \times 1,00797 \; \text{u}\\
        & \Rightarrow m_{kg} = `r sci_fmt(py$m_H, digits=4)` \; \text{kg}
      \end{align*}
      \item Oxigênio
      \begin{align*}
        m_{kg} = \dfrac{1,6604 \times 10^{-27} \; \text{kg}}{1\;\text{u}} \times m_{u} & \Rightarrow m_{kg} = \dfrac{`r sci_fmt(py$u, digits=5)`\; \text{kg}}{1\; \text{u}} \times `r format(py$m_O_u, decimal.mark=",", big.mark=".")`\; \text{u}\\
        &\Rightarrow m_{kg} = `r sci_fmt(py$m_O, digits=4)` \; \text{kg}
      \end{align*}
    \end{enumerate}
  \fimSol
  %%%%
  \item Quantas moléculas, cada uma composta por um átomo de oxigênio e dois de hidrogênio, existem num grama de água? Quantas existem em 18 gramas? Quantas em um centímetro cúbico?\\
  \iniSol
    Conforme problema 2.1, sejam $m_{H} = `r sci_fmt(py$m_H, digits=4)`$ kg e $m_{O} = `r sci_fmt(py$m_O, digits=4)`$ kg, as massas de um átomo de Hidrogênio (H) e um átomo de Oxigênio (O), respectivamente. Assim, a massa de uma molécula de água, composta por 2 átomos H e um átomo O é:
    $$
      m_{H_2O} = 2 \cdot `r sci_fmt(py$m_H, digits=4)` + `r sci_fmt(py$m_O, digits=4)` = `r sci_fmt(py$m_h2o, digits=4)` \; \text{kg}
    $$
    Portanto, em 1 grama ($10^{-3}$ kg) de água, temos:
    $$
    N_{1g} = \dfrac{10^{-3}}{m_{H_2O}} = \dfrac{10^{-3}}{`r sci_fmt(py$m_h2o, digits=4)`} = `r sci_fmt(py$N_1g, digits=3)` \; \text{moléculas}
    $$
    Em 18 gramas de água, teremos:
    $$
    N_{18g} = 18 \; \text{g}  \cdot  \dfrac{N_{1g} \; \text{moléculas}}{1\; \text{grama}}= 18 \cdot `r sci_fmt(py$N_1g, digits=4)`  = `r sci_fmt(py$N_18g, digits=3)` \; \text{moléculas} 
    $$
    Finalmente, sabendo que a densidade da água é 1 g/cm$^3$, em 1 cm$^3$ haverá $`r sci_fmt(py$N_1g, digits=3)`$ moléculas de água.
  \fimSol
  %%%%
  \item Na Seç. 2.3 foi mencionado que quilograma poderia ser definido como sendo igual à massa de $`r sci_fmt(py$N_C_1kg, digits=5)`$ átomos so isótopo $^{12}$C, cuja massa é definida como sendo exatamente `r format(py$m_C_u, nsmall=4, decimal.mark=",", big.mark=".")` u. Verifique se essa definição é compatível com o valor de u dado no Prob. 2.1.\\
  \iniSol
    \begin{align*}
      \dfrac{m_{kg}}{m_{u}} = \dfrac{1 \; \text{kg}}{`r sci_fmt(py$N_C_1kg, digits=5)` \; \text{átomos} \times  `r format(py$m_C_u, nsmall=4, decimal.mark=",", big.mark=".")`\;\text{u / átomo}} = `r sci_fmt(py$m_C, digits=5)`\; \text{kg/u}
    \end{align*}
  \fimSol
  %%%%
  \item Considere as moléculas de hidrogênio, de oxigênio e de nitrogênio, cada uma delas composta por dois átomos idênticos. Calcule o número de moléculas de cada um desses gases, nas condições normais de pressão e temperatura (TPN) existentes em 1 m$^3$. Use os valores das densidades relativas dadas na Tab. 2.2. Faça uma extensão do seu cálculo que seja válida para outros gases. Qual é a conclusão que você pode tirar dos seus resultados?\\
  \iniSol
  Sejam $\rho$, a densidade do gás em kg/m$^3$, $m$, a massa de cada molécula, em kg. Então, a quantidade $N$ de moléculas por unidade de volume é tal que: 
  $$
  \rho = \dfrac{N \times m }{1} \Rightarrow N = \dfrac{\rho}{m}
  $$
  Para cada um dos gases listados, temos:
  \begin{enumerate}[label=\textbf{(\roman*)}]
    \item Hidrogênio (H$_2$)
    Cada molécula de gás tem massa de cada molécula:
    \begin{align*}
      m_{H_2 (kg)} = 2 \times m_{H_2 (u)} \times u &= 2 \times `r sci_fmt(py$m_H_u, digits=6)` \; \text{kg/u} \times `r sci_fmt(py$u, digits=5)`\; \text{u} \\
      &= `r sci_fmt(py$m_H2, digits=5)` \; \text{kg}
    \end{align*}
    e densidade igual a $\rho_{H_2} = `r sci_fmt(py$rho_H2, digits=5)`$ kg/m$^3$. Portanto, a quantidade de moléculas em 1 metro cúbico é igual a:
    $$
    N_{H_2} = \dfrac{\rho_{H_2}}{m_{H_2}} = \dfrac{`r sci_fmt(py$rho_H2, digits=5)` \; \text{kg/m}^3}{`r sci_fmt(py$m_H2, digits=4)` \; \text{kg/molécula}} = `r sci_fmt(py$N_H2, digits=4)` \; \text{moléculas/m}^3
    $$
    %%
    \item Oxigênio (O$_2$)
    Cada molécula de gás tem massa de cada molécula:
    \begin{align*}
      m_{O_2 (kg)} = 2 \times m_{O_2 (u)} \times u &= 2 \times `r sci_fmt(py$m_O_u, digits=6)` \; \text{kg/u} \times `r sci_fmt(py$u, digits=5)`\; \text{u} \\
      &= `r sci_fmt(py$m_O2, digits=5)` \; \text{kg}
    \end{align*}
    e densidade igual a $\rho_{O_2} = `r sci_fmt(py$rho_O2, digits=5)`$ kg/m$^3$. Portanto, a quantidade de moléculas em 1 metro cúbico é igual a:
    $$
    N_{O_2} = \dfrac{\rho_{O_2}}{m_{O_2}} = \dfrac{`r sci_fmt(py$rho_O2, digits=5)` \; \text{kg/m}^3}{`r sci_fmt(py$m_O2, digits=4)` \; \text{kg/molécula}} = `r sci_fmt(py$N_O2, digits=4)` \; \text{moléculas/m}^3
    $$
    %%
    \item Nitrogênio (N$_2$)
    Cada molécula de gás tem massa de cada molécula:
    \begin{align*}
      m_{N_2 (kg)} = 2 \times m_{N_2 (u)} \times u &= 2 \times `r sci_fmt(py$m_N_u, digits=6)` \; \text{kg/u} \times `r sci_fmt(py$u, digits=5)`\; \text{u} \\
      &= `r sci_fmt(py$m_N2, digits=5)` \; \text{kg}
    \end{align*}
    e densidade igual a $\rho_{N_2} = `r sci_fmt(py$rho_N2, digits=5)`$ kg/m$^3$. Portanto, a quantidade de moléculas em 1 metro cúbico é igual a:
    $$
    N_{N_2} = \dfrac{\rho_{N_2}}{m_{N_2}} = \dfrac{`r sci_fmt(py$rho_N2, digits=5)` \; \text{kg/m}^3}{`r sci_fmt(py$m_N2, digits=4)` \; \text{kg/molécula}} = `r sci_fmt(py$N_N2, digits=4)` \; \text{moléculas/m}^3
    $$
  \end{enumerate}
  Os resultados acima parecem indicar que, nas condições normais de pressão e temperatura (TPN), a quantidade de moléculas de gás por unidade de volume é uma constante, nesse caso, aproximadamente igual a $2,69 \times 10^{22}$ moléculas por metro cúbico.
  \fimSol
  %%%%
  \item Admitindo-se que o ar é composto por 20\% de oxigênio e 80\% de nitrogênio, e que esses gases formam moléculas diatômicas, calcule a massa molecular ``efetiva'' do ar. Avalie o múmero de moléculas em 1 cm$^3$ de ar nas condições TPN. Quantas moléculas são de oxigênio e quantas são de nitrogênio?\\
  \iniSol
  \begin{itemize}
    \item[] \textbf{Primeira Parte:}
    Seja $N_{Ar}$ a quantidade de moléculas de ar presentes em um dado volume $V$. Supondo que o ar é composto por 20\% de oxigênio e 80\% de nitrogênio, temos: $$N_{Ar} = N_{O_2} + N_{N_2},$$
    em que $N_{O_2} = 0,2N_{Ar}$ é a quantidade de moléculas (diatômicas) de Oxigênio e  $N_{N_2} = 0,8N_{Ar}$ é a quantidade de moléculas (diatômicas) de Nitrogênio.
    %%
    Por outro lado, a massa total de ar é $$M_{Ar} = N_{O_2} \cdot m_{O_2} + N_{N_2}  \cdot m_{N_2},$$
    onde $m_{O_2}$ e $m_{N_2}$ são respectivamente as massas moleculares do Oxigênio e do Nitrogênio. 
    %%
    Portanto, a massa molecular do ar será:
    \begin{align*}
      m_{Ar} &= \dfrac{M_{Ar}}{N_{Ar}} = \dfrac{N_{O_2} \cdot m_{O_2} + N_{N_2}  \cdot m_{N_2}}{N_{Ar}} = \dfrac{N_{O_2}}{N_{Ar}} m_{O_2} + \dfrac{N_{N_2}}{N_{Ar}} m_{N_2}\\
      m_{Ar} &= 0,2 m_{O_2} + 0,8 m_{N_2}
    \end{align*}
    Em unidades de massa atômica (u) e em quilogramas (kg), temos:
    \begin{align*}
      m_{Ar} &= 0,2 \cdot (2 \cdot `r sci_fmt(py$m_O_u, digits=6)`) + 0,8 \cdot (2 \cdot `r sci_fmt(py$m_N_u, digits=6)`)) = `r sci_fmt(py$m_Ar_u, digits=4)` \; \text{u/molécula}\\
      &= (`r sci_fmt(py$m_Ar_u, digits=4)` \; \text{u/molécula}) \cdot (`r sci_fmt(py$u, digits=6)` \; \text{kg/u}) = `r sci_fmt(py$m_Ar, digits=4)` \; \text{kg/molécula}
    \end{align*}
    %%
    \item[] \textbf{Segunda Parte:}
    Seja $M_{Ar} = M_{O_2} + M_{N_2}$ massa total de ar em um volume $V$ em função das massas de oxigênio ($M_{O_2}$) e nitrogênio ($M_{N_2}$). Dividindose por $V$, e considerendo que 20\% do ar é composto de oxigênio e 80\%, de nitrogênio, temos:
    \begin{align*}
      \dfrac{M_{Ar}}{V} = \dfrac{M_{O_2} + M_{N_2}}{V} &\Rightarrow \dfrac{M_{Ar}}{V} = \dfrac{M_{O_2}}{V} + \dfrac{M_{N_2}}{V}\\
      &\Rightarrow \dfrac{M_{Ar}}{V} = 0,2 \dfrac{M_{O_2}}{0,2V} + 0,8 \dfrac{M_{N_2}}{0,8V}\\
      &\Rightarrow \dfrac{M_{Ar}}{V} = 0,2 \rho_{O_2} + 0,8 \rho_{N_2}
    \end{align*}
    Na última passagem, observamos o fato de que $\dfrac{M_{O_2}}{0,2V}$ é a massa específica do oxigênio $\rho_{O_2}$ e $\dfrac{M_{N_2}}{0,8V}$ é a massa específica do nitrogênio $\rho_{N_2}$.\\
    %%
    Lembrando que na primeira parte deste problema determinamos a massa molecular do ar como $m_{Ar} = \dfrac{M_{Ar}}{N_{Ar}} \Rightarrow M_{Ar} = m_{Ar} N_{Ar}$, podemos determinar a quantidade de moléculas de ar por unidade de volume da seguinte forma:
    \begin{align*}
      \dfrac{M_{Ar}}{V} = 0,2 \rho_{O_2} + 0,8 \rho_{N_2} &\Rightarrow \dfrac{m_{Ar} N_{Ar}}{V} = 0,2 \rho_{O_2} + 0,8 \rho_{N_2}\\ 
      &\Rightarrow \dfrac{N_{Ar}}{V} = \dfrac{0,2 \rho_{O_2} + 0,8 \rho_{N_2}}{m_{ar}}\\
      &\Rightarrow \dfrac{N_{Ar}}{V} = \dfrac{0,2 \cdot \left(`r sci_fmt(py$rho_O2, digits=4)` \; \text{g/cm}^3\right) + 0,8 \cdot \left(`r sci_fmt(py$rho_N2, digits=4)`\; \text{g/cm}^3\right)}{\left(`r sci_fmt(py$m_Ar, digits=4)`\; \text{kg/molécula}\right) \cdot \left(1000 \; \text{g/kg}\right))}\\
      &\Rightarrow \dfrac{N_{Ar}}{V} = \dfrac{\left(`r sci_fmt(0.2*py$rho_O2, digits=4)` \; \text{g/cm}^3\right) + \left(`r sci_fmt(0.8*py$rho_N2, digits=4)` \; \text{g/cm}^3\right)}{`r sci_fmt(1000*py$m_Ar, digits=4)`\; \text{g/molécula}}\\
      &\Rightarrow \dfrac{N_{Ar}}{V} = \dfrac{`r sci_fmt(0.2*py$rho_O2 + 0.8*py$rho_N2, digits=4)` \; \text{g/cm}^3}{`r sci_fmt(1000*py$m_Ar, digits=4)`\; \text{kg/molécula}}\\
      &\Rightarrow \dfrac{N_{Ar}}{V} = `r sci_fmt(py$N_Ar, digits=4)` \; \text{moléculas/cm}^3
    \end{align*}
    Do total teremos
      \begin{align*}
        &N_{O_2} = 0,2 \cdot N_{Ar} = 0,2 \cdot `r sci_fmt(py$N_Ar, digits=4)` = `r sci_fmt(py$N_O2, digits=4)`\; \text{moléculas de oxigênio; e}\\
        &N_{N_2} = 0,8 \cdot N_{Ar} = 0,8 \cdot `r sci_fmt(py$N_Ar, digits=4)` = `r sci_fmt(py$N_N2, digits=4)`\; \text{moléculas de nitrogênio}
      \end{align*}
  \end{itemize}
  \fimSol
  %%%% Fim do Problema 2.5
  \item A densidade do gás interestelar na nossa galáxia é avaliada em cerca de $10^{-21}\;\text{kg/m}^{-3}$. Admitindo-se que esse gás é constituído principalmente de hidrogênio, avalie o número de átomos de hidrgênio por $\text{cm}^3$. Compare esse resultado com o correspondente obtido para o ar nas condições TPN (Prob. 2.5).\\
  \iniSol
    Em um volume $V$, teremos a massa $M = \rho \cdot V = m_{H} \cdot N$, em que $\rho = 10^{-21} \; \text{kg/m}^3$ é a densidade do gás interestelar, $m_{H} = `r sci_fmt(py$m_H, digits=4)` \; \text{kg/molécula}$ é a massa molecular do átomo de hidrogênio e $N$ é a quantidade de moléculas presentes no volume $V$. Assim,  
    \begin{align*}
      M = \rho \cdot V = m_{H} \cdot N &\Rightarrow \dfrac{N}{V} = \dfrac{\rho}{m_{H}} = \dfrac{`r sci_fmt(py$rho_space, digits=4)`\; \text{kg/m}^3}{`r sci_fmt(py$m_H, digits=4)`\; \text{kg/molécula}}\\
      &\Rightarrow \dfrac{N}{V} = `r sci_fmt(py$N_space, digits=4)` \; \text{moléculas/m}^3 \approx `r sci_fmt(py$N_space * 1e-6, digits=2)` \; \text{moléculas/cm}^3
    \end{align*}
  \fimSol
  %%%% Fim do Problema 2.6
  \item Um como de 2 cm de raio contém água. Em duas horas, o nível da água baixa 1mm. Avalie, em gramas por hora, a velocidade de evaporação da água. Quantas moléculas de água estão se evaporando por secundo em cada centímetro quadrado da superfície da água? (Sugerimos que o estudante realize esta experiência e obtenha seus próprios dados. Por que você obtém resultados diferentes cada dia?).\\
  \iniSol
   Consideremos que em  um intervalo de tempo $\Delta t$, a quantidade de massa de água evaporada seja $\Delta m = \rho_{H_2O} \Delta V$, em que $\rho_{H_2O} = 1 \; \text{g/cm}^3$ é a densidade da água e $\Delta V$ é o volume de água evaporado. Para um copo cilíndrico de raio $r = 2$ cm, se a altura do copo baixa $\Delta h = 1\;\text{mm} = 0,1\; \text{cm}$ em $\Delta t = 2 $ horas, a velocidade $v$ de evaporação será:
   \begin{align*}
    v &= \dfrac{\Delta m}{\Delta t} = \dfrac{\rho_{H_2O} \Delta V}{ \Delta t} = \dfrac{\rho_{H_2O} \left(\pi r^2 \Delta h\right)}{\Delta t}\\
    v &= \pi r^2 \rho_{H_2O}  \dfrac{\Delta h}{\Delta t}\\
    v &= \pi \cdot \left(2 \; \text{cm}\right)^2 \cdot \left(`r sci_fmt(py$rho_agua, digits=2)` \; \text{g/cm}^3\right) \cdot \dfrac{0,1 \; \text{cm}}{2 \; \text{h}}\\
    v &= `r sci_fmt(py$v_evap, digits=3)` \; \text{g/h}
   \end{align*}
   Sabendo que a massa molecular da água é 
   
   \begin{align*}
    m_{H_2O} = 2 \cdot m_{H} + m_{O} &= 2 \cdot \left( `r sci_fmt(py$m_H, digits=4)` \; \text{kg/molécula}\right) + \left( `r sci_fmt(py$m_O, digits=4)` \; \text{kg/molécula}\right)\\
    &= `r sci_fmt(py$m_h2o, digits=4)` \; \text{kg/molécula}\\
    &= `r sci_fmt(1000*py$m_h2o, digits=4)` \; \text{g/molécula}
   \end{align*}
   
   Retornemos à equação básica para a taxa de evaporação $v = \dfrac{\Delta m}{\Delta t}$. Seja $\Delta m = m_{H_2O} \cdot \Delta N$, em que $m_{H_2O} = `r sci_fmt(py$m_h2o, digits=4)`$ kg/molécula (Ver Probl. 2.2) e $\Delta N$ é a quantidade de moléculas que se evaporaram no intervalo de tempo $\Delta t$.   Assim, 
   \begin{align*}
    v = \dfrac{\Delta m}{\Delta t} \Rightarrow v = \dfrac{m_{H_2O} \Delta N}{\Delta t} \Rightarrow \dfrac{\Delta N}{\Delta t} = \dfrac{v}{m_{H_2O}}
   \end{align*}
   Finalmente, a quantidade de moléculas se evaporando por segundo em cada cemtímetro quadrado da superfície da água é ($S = \pi r^2$)
   \begin{align*}
    \dfrac{\Delta N}{S \Delta t} &= \dfrac{v}{\pi r^2 \cdot m_{H_2O}} = \dfrac{\left(`r sci_fmt(py$v_evap, digits=4)`\; \dfrac{\text{g}}{\text{h}}\right) \cdot \left(\dfrac{1\;\text{kg}}{1000\;\text{g}}\right) \cdot \left(\dfrac{1\;\text{h}}{3600\;\text{s}}\right)}{\pi \left(2 \; \text{cm}\right)^2 \cdot \left(`r sci_fmt(py$m_h2o, digits=4)` \; \text{kg/molécula}\right)}\\
    &= `r sci_fmt(py$dNdt_evap, digits=4)` \; \text{moléculas} \cdot  \text{cm}^{-2} \cdot \text{s}^{-1} 
   \end{align*}
  \fimSol
  %%%% Fim do Problema 2.7
  \item Um \textit{mol} de uma substância é definido como sendo uma quantidade dessa substância, expressa em \textit{gramas}, numericamente igual à massa molecular dessa substância em u. (Quando nos referimos a um elemento químico, e não a um composto, usaremos massa atômica em vez de massa molecular.) Verifique que o número de moléculas (ou de átomos) em um mol de \textit{qualquer} substância é sempre o mesmo e é igual a $6,0225 \times 10^{23}$. Este número, chamado \textit{constante de Avogrado}, é uma constante física muito importante.\\
  \iniSol
  Seja $1 \; \text{u} = `r sci_fmt(py$u, digits=5)`\;\text{kg} \Rightarrow 1\; \text{u} = `r sci_fmt(1000*py$u, digits=5)`\; \text{g}$. Consideremos uma substância (átomo ou molécula) cuja massa molecular em unidade de massa atômica seja $m = k\; \text{u}$, em que $K$ é uma constante positiva.\\
  %%
  Nesse caso, considerando a definição dada, 1 \textit{mol} dessa substância tem massa, em gramas, igual a $M = K\; \text{g}$. A quantidadde de entidades(átomos ou moléculas) dessa substância será $N_{A}$ tal que:
  \begin{align*}
    M = m \cdot N_{A} \Rightarrow N_A = \dfrac{M}{m} &= \dfrac{K \; \text{g}}{\left(K\; \text{u/entidade}\right) \cdot \left(\dfrac{`r sci_fmt(1000*py$u, digits=5)`\; \text{g}}{1\; \text{u}}\right)}\\
    &= \dfrac{1}{`r sci_fmt(1000*py$u, digits=5)`} \; \text{entidades}\\
    &= `r sci_fmt(1/(1000*py$u), digits=5)` \; \text{entidades (átomos ou moléculas)} 
  \end{align*}
  \fimSol
  %%%% Fim do Problema 2.8
  \item Usando os dados das Tabs 2.2 e A.1, avalie a separação média entre as moléculas nas condições TPN, no hidrogênio (gás), na água (líquido) e no ferro (sólido).\\
  \iniSol
  Consideremos determinada quantidade de substância de densidade $\rho$, ocupando um volume $V$. A massa presente nesse volume é $M = m \cdot N$ em que $m$ é a massa molecular e $N$ é a quantidade de moléculas presentes. Determinemos o volume médio por molécula ($V/N$):
  \begin{align*}
    \rho = \dfrac{M}{V} \Rightarrow \rho = \dfrac{m \cdot N}{V} \Rightarrow \dfrac{V}{N} = \dfrac{m}{\rho}
  \end{align*}
  \textbf{Modelo Cúbico:} Consideremos que esse volume médio por molécula seja um cubo de lado $l$. Assim, a distância média entre as moléculas será:
  $$
    l = \sqrt[3]{\frac{V}{N}} \Rightarrow l = \sqrt[3]{\dfrac{m}{\rho}}
  $$
  Aplicando a fórmula acima às substâncias dadas, temos:
  \begin{itemize}
    \item[] \textbf{Hidrogênio:}
    \begin{align*}
      l = \sqrt[3]{\dfrac{m}{\rho}} = \sqrt[3]{\dfrac{`r sci_fmt(py$m_H2, digits=4)` \; \text{kg}}{`r sci_fmt(1000*py$rho_H2, digits=4)`\; \text{kg/m}^3}} = \sqrt[3]{`r sci_fmt(py$vol_H2, digits=4)` \; \text{m}^3} = `r sci_fmt(py$l_H2, digits=3)` \; \text{m}
    \end{align*}
    \item[] \textbf{Água:}
    \begin{align*}
      l = \sqrt[3]{\dfrac{m}{\rho}} = \sqrt[3]{\dfrac{`r sci_fmt(py$m_H2O, digits=4)` \; \text{kg}}{`r sci_fmt(1000*py$rho_H2O, digits=4)`\; \text{kg/m}^3}} = \sqrt[3]{`r sci_fmt(py$vol_H2O, digits=4)` \; \text{cm}^3} = `r sci_fmt(py$l_H2O, digits=4)` \; \text{m}
    \end{align*}
    \item[] \textbf{Ferro:}
    \begin{align*}
      l = \sqrt[3]{\dfrac{m}{\rho}} = \sqrt[3]{\dfrac{`r sci_fmt(py$m_Fe, digits=4)` \; \text{kg}}{`r sci_fmt(1000*py$rho_Fe, digits=4)`\; \text{kg/m}^3}} = \sqrt[3]{`r sci_fmt(py$vol_Fe, digits=4)` \; \text{m}^3} = `r sci_fmt(py$l_Fe, digits=4)` \; \text{m}
    \end{align*}
  \end{itemize}
  \textbf{Modelo esférico:} Consideremos que o volume médio por molécula seja uma esfera de diâmetro $D$. Assim, a distância média entre as moléculas será:
  $$
    \dfrac{V}{N} = \dfrac{\pi D^3}{6} \Rightarrow D = \sqrt[3]{\dfrac{6}{\pi} \dfrac{V}{N}} \Rightarrow D = \sqrt[3]{\dfrac{6}{\pi} \dfrac{m}{\rho}} 
  $$
  Aplicando a fórmula acima às substâncias dadas, temos:
  \begin{itemize}
    \item[] \textbf{Hidrogênio:}
    \begin{align*}
      D = \sqrt[3]{\dfrac{6}{\pi}\dfrac{m}{\rho}} = \sqrt[3]{\dfrac{6}{\pi} \cdot \dfrac{`r sci_fmt(py$m_H2, digits=4)` \; \text{kg}}{`r sci_fmt(1000*py$rho_H2, digits=4)`\; \text{kg/m}^3}}  = `r sci_fmt(py$D_H2, digits=3)` \; \text{m}
    \end{align*}
    \item[] \textbf{Água:}
    \begin{align*}
      D = \sqrt[3]{\dfrac{6}{\pi}\dfrac{m}{\rho}} = \sqrt[3]{\dfrac{6}{\pi} \cdot \dfrac{`r sci_fmt(py$m_H2O, digits=4)` \; \text{kg}}{`r sci_fmt(1000*py$rho_H2O, digits=4)`\; \text{kg/m}^3}} =  `r sci_fmt(py$D_H2O, digits=4)` \; \text{m}
    \end{align*}
    \item[] \textbf{Ferro:}
    \begin{align*}
      D = \sqrt[3]{\dfrac{6}{\pi}\dfrac{m}{\rho}} = \sqrt[3]{\dfrac{6}{\pi} \cdot \dfrac{`r sci_fmt(py$m_Fe, digits=4)` \; \text{kg}}{`r sci_fmt(1000*py$rho_Fe, digits=4)`\; \text{kg/m}^3}} =  `r sci_fmt(py$D_Fe, digits=4)` \; \text{m}
    \end{align*}
  \end{itemize}
  \fimSol
\end{enumerate}